### PR TITLE
Add greeting action

### PR DESCRIPTION
**Pull request by hello-smile6**
We need this. Let's go.

### CODE REVIEW

**Comment by MystPi** [comment]
What does this do and why do we need it?

**Comment by kccuber-scratch** [comment]
@MystPi this is not needed, it probably just says thank you for contributing to ninetails

**Comment by MystPi** [comment]
Thanks for the warning, @kccuber-scratch. @hello-smile6, why would you try to do this?

**Comment by webdev03** [comment]
@hello-smile6 why??

**Comment by kccuber-scratch** [comment]
> Thanks for the warning, @kccuber-scratch. hello-smile6, why would you try to do this?

they did the same with Freecat when that was still a thing, soooo

**Comment by hello-smile6** [comment]
I thought a rickroll would be nice.

**Pull request closed without merging**
