### PR TITLE
fix: update available message showing on new tab

### PR DESCRIPTION
**Pull request by webdev03**
@JaydenDev caught this on https://scratch.mit.edu/discuss/post/5863482/

Not tested yet, I am about to

### CODE REVIEW

**Comment by webdev03** [comment]
Okay, it is broken, I am trying to fix it

**Comment by MystPi** [comment]
Yes, this should work, and I'll add this to a future version. However, right now I'll just edit ninetails.cf to hide it if no "v" query parameter is present.

**Comment by webdev03** [comment]
how are there 2 commits with the same thing in it?!

**Comment by MystPi** [comment]
What?

**Comment by webdev03** [comment]
image
https://github.com/MystPi/ninetails/commits?author=webdev03

**Comment by MystPi** [comment]
Hm, that's interesting.

**Comment by webdev03** [comment]
I think it might just be a rebase merge.

**Pull request merged**
