### PR TITLE
Search Engine presets.

### PR DESCRIPTION
**Pull request by Darth-Ness**
This will allow you to pick some default options for search engines.

To Do:
Fix Styling - I don't know TailWindCSS, so I don't know how to fix it.
Actually make buttons change SE - I can do this since I know JS.

### CODE REVIEW

**Comment by dnlnrs** [comment]
Maybe it could be useful to do a `select` instead of buttons?
Let me know what you think.

**Comment by Darth-Ness** [comment]
> Maybe it could be useful to do a `select` instead of buttons? Let me know what you think.

What would the difference be?

**Comment by MystPi** [comment]
> Maybe it could be useful to do a `select` instead of buttons? Let me know what you think.

Select would be much preferable.

**Comment by MystPi** [comment]
> > Maybe it could be useful to do a `select` instead of buttons? Let me know what you think.
> 
> What would the difference be?

A `select` element is a dropdown picker. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by Darth-Ness** [comment]
All right, I'll try that out. All though, I'll have to fix the conflicts in my branch now. So I change buttons to select afterwards.

**Pull request closed without merging**
