### PR TITLE
add release detection to ninetails

### LINKED ISSUE #8: Idea: Auto updating
There could be a way to automatically update Ninetails. I think that you can use https://www.electronjs.org/docs/latest/api/auto-updater/ or maybe you can fetch from Github API to see if a new release is out.

I can work on the Github API one if you want.

### PR DESCRIPTION
**Pull request by webdev03**
adds release detection, should resolve #8

### CODE REVIEW

**Comment by webdev03** [comment]
Wait, I think I messed up the styling of index.js oh no.. I think I need to have a style guide

**Comment by MystPi** [comment]
If it's okay, tomorrow I'm going to implement my own version that's more Ninetails-y.

(Also your editor messed up the indentation. 😜)

**Comment by webdev03** [comment]
Oh LOL
Thanks :smile:

**Comment by MystPi** [comment]
> Oh LOL Thanks 😄 edit: how would I fix the indentation, in the future?

Just don't format the code with your editor (you also messed up the quotes), and use 2 spaces instead of 4 for tabs.

**Comment by webdev03** [comment]
Oh ok thanks!

**Comment by MystPi** [comment]
Implemented in v2.1.0! (#19)

**Pull request closed without merging**
