### PR TITLE
Revert "Revert the revert"

### PR DESCRIPTION
**Pull request by MystPi**
Wow. We really are turning into Freecat.
Reverts MystPi/ninetails#71

### CODE REVIEW

**Comment by ninjamar** [comment]
fyi you should test your pr's before

**Comment by MystPi** [comment]
> fyi you should test your pr's before

Wasn't my PR, it was dnlnrs'.

**Comment by ninjamar** [comment]
> > fyi you should test your pr's before
> 
> Wasn't my PR, it was dnlnrs'.

they should test it before making the pr

**Comment by MystPi** [comment]
> > > fyi you should test your pr's before
> > 
> > 
> > Wasn't my PR, it was dnlnrs'.
> 
> they should test it before making the pr

They did; they accidentally pushed the wrong thing.

**Comment by ninjamar** [comment]
> > > > fyi you should test your pr's before
> > > 
> > > 
> > > Wasn't my PR, it was dnlnrs'.
> > 
> > 
> > they should test it before making the pr
> 
> They did; they accidentally pushed the wrong thing.

oh

**Comment by hello-smile6** [comment]
> Wow. We really are turning into Freecat. Reverts #71

Yeah!

**Comment by webdev03** [comment]
Revert "Revert "Revert "Revert "setup electron store""""

**Pull request merged**
