### PR TITLE
Ctrl-Click Tab to delete (there might be a better keybind, such as Backspace-Click)

### PR DESCRIPTION
**Pull request by ScolderCreations**

### CODE REVIEW

**Comment by MystPi** [comment]
Good idea!

**Comment by MystPi** [comment]
I'll add this to v2.2.4. Sorry for the merge conflict.

**Comment by MystPi** [comment]
Done in https://github.com/MystPi/ninetails/commit/bf405afcefe8528d90e8b32b64d03e3bce50ab14 on the v2.2.4 branch.

**Comment by ScolderCreations** [comment]
> Done in [bf405af](https://github.com/MystPi/ninetails/commit/bf405afcefe8528d90e8b32b64d03e3bce50ab14) on the v2.2.4 branch.

Thanks!

**Comment by MystPi** [comment]
> > Done in [bf405af](https://github.com/MystPi/ninetails/commit/bf405afcefe8528d90e8b32b64d03e3bce50ab14) on the v2.2.4 branch.
> 
> Thanks!

No problem; thanks for the great idea!

**Pull request closed without merging**
