### PR TITLE
Version 2.2.6, with a severe bug fix and more

### PR DESCRIPTION
**Pull request by MystPi**
Release notes are, well, in the release notes.

### CODE REVIEW

**Comment by hello-smile6** [comment]
> Release notes are, well, in the release notes.

Why not use `main` as the <b>main</b> branch?

**Comment by MystPi** [comment]
> > Release notes are, well, in the release notes.
> 
> Why not use `main` as the main branch?

You should never make changes directly to the main branch.

**Comment by hello-smile6** [comment]
> > > Release notes are, well, in the release notes.
> > 
> > 
> > Why not use `main` as the main branch?
> 
> You should never make changes directly to the main branch.

Well, I do all the time on SpellCheckJS.

**Comment by hello-smile6** [comment]
> > > > > Release notes are, well, in the release notes.
> > > > 
> > > > 
> > > > Why not use `main` as the main branch?
> > > 
> > > 
> > > You should never make changes directly to the main branch.
> > 
> > 
> > Well, I do all the time on SpellCheckJS.
> 
> It doesn't really matter unless you have a large-ish repo.

_Do_ you have a large-ish repo? Also, @llk commits to `main`.

**Comment by kccuber-scratch** [comment]
why roboto? I think it's fairly overused being the number 1 font on Google Fonts. Something like [Inter](https://rsms.me/inter) deserved this role IMO

**Comment by MystPi** [comment]
> why roboto? I think it's fairly overused being the number 1 font on Google Fonts. Something like [Inter](https://rsms.me/inter) deserved this role IMO

I like Roboto, plus it looks nice in Ninetails. I didn't choose it because it's number one on Google Fonts.

**Comment by hello-smile6** [comment]
> > why roboto? I think it's fairly overused being the number 1 font on Google Fonts. Something like [Inter](https://rsms.me/inter) deserved this role IMO
> 
> I like Roboto, plus it looks nice in Ninetails. I didn't choose it because it's number one on Google Fonts.

Saying people choose things because they're popular is like saying people try to make software work because it's fun.

**Comment by MystPi** [comment]
> > > why roboto? I think it's fairly overused being the number 1 font on Google Fonts. Something like [Inter](https://rsms.me/inter) deserved this role IMO
> > 
> > 
> > I like Roboto, plus it looks nice in Ninetails. I didn't choose it because it's number one on Google Fonts.
> 
> Saying people choose things because they're popular is like saying people try to make software work because it's fun.

I just said I **didn't** choose it because it was popular.

**Comment by hello-smile6** [comment]
> > > > why roboto? I think it's fairly overused being the number 1 font on Google Fonts. Something like [Inter](https://rsms.me/inter) deserved this role IMO
> > > 
> > > 
> > > I like Roboto, plus it looks nice in Ninetails. I didn't choose it because it's number one on Google Fonts.
> > 
> > 
> > Saying people choose things because they're popular is like saying people try to make software work because it's fun.
> 
> I just said I **didn't** choose it because it was popular.

I know. Also, could Ninetails work on 32-bit Ubuntu 10?

**Comment by MystPi** [comment]
> > > > > why roboto? I think it's fairly overused being the number 1 font on Google Fonts. Something like [Inter](https://rsms.me/inter) deserved this role IMO
> > > > 
> > > > 
> > > > I like Roboto, plus it looks nice in Ninetails. I didn't choose it because it's number one on Google Fonts.
> > > 
> > > 
> > > Saying people choose things because they're popular is like saying people try to make software work because it's fun.
> > 
> > 
> > I just said I **didn't** choose it because it was popular.
> 
> I know. Also, could Ninetails work on 32-bit Ubuntu 10?

I don't know, but you can try installing the .deb build.

**Comment by hello-smile6** [comment]
> > > > > > why roboto? I think it's fairly overused being the number 1 font on Google Fonts. Something like [Inter](https://rsms.me/inter) deserved this role IMO
> > > > > 
> > > > > 
> > > > > I like Roboto, plus it looks nice in Ninetails. I didn't choose it because it's number one on Google Fonts.
> > > > 
> > > > 
> > > > Saying people choose things because they're popular is like saying people try to make software work because it's fun.
> > > 
> > > 
> > > I just said I **didn't** choose it because it was popular.
> > 
> > 
> > I know. Also, could Ninetails work on 32-bit Ubuntu 10?
> 
> I don't know, but you can try installing the .deb build.

Could you build a 32-bit .deb ?

**Comment by MystPi** [comment]
> Could you build a 32-bit .deb ?

I have a 64 bit machine, so I can't unfortunately.

**Comment by hello-smile6** [comment]
> > Could you build a 32-bit .deb ?
> 
> I have a 64 bit machine, so I can't unfortunately.

You can build 32-bit binaries on a 64-bit OS.

**Comment by MystPi** [comment]
> > > Could you build a 32-bit .deb ?
> > 
> > 
> > I have a 64 bit machine, so I can't unfortunately.
> 
> You can build 32-bit binaries on a 64-bit OS.

Then the existing build should work, right? Did you even try it?

**Comment by hello-smile6** [comment]
> > > > Could you build a 32-bit .deb ?
> > > 
> > > 
> > > I have a 64 bit machine, so I can't unfortunately.
> > 
> > 
> > You can build 32-bit binaries on a 64-bit OS.
> 
> Then the existing build could work, right? Did you even try it?

Going to

**Pull request merged**
