### PR TITLE
fix: db error con missing config

### PR DESCRIPTION
**Pull request by dnlnrs**

### CODE REVIEW

**Comment by dnlnrs** [comment]
@MystPi If I didn't screwed something doing the PR this includes everything from the store PR and the fix.

**Comment by MystPi** [comment]
Thanks!

**Comment by dnlnrs** [comment]
🤔 I will check downloading the 2.2.4 branch

**Comment by MystPi** [comment]
So the original error was fixed, but now when you save your settings it gives a similar error.

**Comment by MystPi** [comment]
Did you actually test your settings DB pull request?

**Comment by dnlnrs** [comment]
> 

Yes, I have Ninetails running right now with my code.
Let me rerun everything and check.

**Comment by dnlnrs** [comment]
@MystPi 
I have another unrelated error
```
Uncaught (in promise) ReferenceError: createTab is not defined
    at startup.js:13
```

**Comment by MystPi** [comment]
> @MystPi I have another unrelated error
> 
> ```
> Uncaught (in promise) ReferenceError: createTab is not defined
>     at startup.js:13
> ```

It didn't say that before your PR... hmm.

**Comment by dnlnrs** [comment]
Found it! 
I'll redo everything and send a new PR, sorry
I have found the problem, was a messed file with local merge. 😞

**Comment by MystPi** [comment]
> Found it! I'll redo everything and send a new PR, sorry I have found the problem, was a messed file with local merge. 😞

Great! It's fine. :)

**Pull request merged**
