### PR TITLE
Add github.dev link for editing

### PR DESCRIPTION
**Pull request by hello-smile6**

### CODE REVIEW

**Comment by Darth-Ness** [comment]
Or person could just push .?

**Comment by hello-smile6** [comment]
> Or person could just push .?

By adding

**Comment by hello-smile6** [comment]
Accidentally closed

**Comment by hello-smile6** [comment]
@MystPi Ready to merge

**Comment by MystPi** [comment]
Can't you just press `ctrl .`?

**Comment by MystPi** [comment]
I don't think this is needed.

**Pull request closed without merging**
