### PR TITLE
Design Changes (2022.17.3/2022.3.17)

### PR DESCRIPTION
**Pull request by JaydenDev**
The changes are the following

- Add consistant border radius, (in the settings, the border radius of the input boxes didn't feel right)
- Reduced size of buttons in settings (they were a bit too big)

Merging this PR is recommended but optional, as it is YOUR software and its your choice and you may not agree with the changes of this PR. If a specific change of this PR is disliked, I will revert it and keep the rest of the changes.

### CODE REVIEW

**Comment by JaydenDev** [comment]
**An extension in my editor has made indention and formatting changes, please review the changes made by the formatter before preceeding to merge this**

**This PR has been entirely tested and bug checked but double checking before merging is always a good idea, although with the specified changes bugs are unlikely**

**Comment by MystPi** [comment]
Could you share a before and after screenshot? Also please don't format the code, only change the code where you need to. This will keep it consistent with the rest of Ninetails' source.

**Comment by JaydenDev** [comment]
Before:
image

After:
image

**Comment by MystPi** [comment]
I'm sorry, but I kind of like the existing one better. Thanks for the idea though!

**Pull request closed without merging**
