### PR TITLE
32bit builds

### PR DESCRIPTION
**Pull request by kccuber-scratch**
Hopefully adds 32 bit builds for linux and windows.

### CODE REVIEW

**Comment by kccuber-scratch** [comment]
ignore the fist 2 commits, i accidentally committed to main on my fork and i should have just made a new branch at that point, but no! i decided to revert that and then make a new branch and then re add the 32 bit build code. 🤦‍♂️

**Comment by kccuber-scratch** [comment]
since it's not working currently, i marked as a draft

**Review by hello-smile6 — APPROVED** [review]
Looks good. At least, I think so.

**Comment by kccuber-scratch** [comment]
> Looks good. At least, I think so.

It _looks_ right, but it keeps failing:
image

**Comment by MystPi** [comment]
Showing the error message would be helpful.

**Comment by kccuber-scratch** [comment]
@MystPi Sorry, here you go:
image

**Comment by kccuber-scratch** [comment]
@mystpi seems good now

**Pull request closed without merging**
