### PR TITLE
Search Engine Presets PR2

### PR DESCRIPTION
**Pull request by Darth-Ness**
I had to delete my old repo so I made a new PR.

### CODE REVIEW

**Review by MystPi — CHANGES_REQUESTED** [review]
Thanks for contributing! I have a few changes that I would like to be made.

- Change the buttons to a `select` element. This will save space and make it easier to use.
- Refrain from using the `onclick` attribute; instead, inside of the `listeners.js` file, use the `change` event listener to listen for changes of the selection.

Here's an example:
```html
<select id="settings-presets">
  <option value="">Select a preset</option>
  <option value="https://example.com"></option>
  ...
</select>
```
```js
byId('settings-presets').addEventListener('change', (e) => {
  ...
});
```

**Comment by Darth-Ness** [comment]
> Thanks for contributing! I have a few changes that I would like to be made.
> 
>     * Change the buttons to a `select` element. This will save space and make it easier to use.
> 
>     * Refrain from using the `onclick` attribute; instead, inside of the `listeners.js` file, use the `change` event listener to listen for changes of the selection.
> 
> 
> Here's an example:
> 
> ```
> <select id="settings-presets">
>   <option value="">Select a preset</option>
>   <option value="https://example.com"></option>
>   ...
> </select>
> ```
> 
> ```js
> byId('settings-presets').addEventListener('change', (e) => {
>   ...
> });
> ```

How do I view the change you requested?

**Comment by hello-smile6** [comment]
> > Thanks for contributing! I have a few changes that I would like to be made.
> > ```
> > * Change the buttons to a `select` element. This will save space and make it easier to use.
> > 
> > * Refrain from using the `onclick` attribute; instead, inside of the `listeners.js` file, use the `change` event listener to listen for changes of the selection.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here's an example:
> > ```
> > <select id="settings-presets">
> >   <option value="">Select a preset</option>
> >   <option value="https://example.com"></option>
> >   ...
> > </select>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > byId('settings-presets').addEventListener('change', (e) => {
> >   ...
> > });
> > ```
> 
> How do I view the change you requested?

I'll just PR into your branch and fix it.

**Comment by MystPi** [comment]
> > Thanks for contributing! I have a few changes that I would like to be made.
> > ```
> > * Change the buttons to a `select` element. This will save space and make it easier to use.
> > 
> > * Refrain from using the `onclick` attribute; instead, inside of the `listeners.js` file, use the `change` event listener to listen for changes of the selection.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here's an example:
> > ```
> > <select id="settings-presets">
> >   <option value="">Select a preset</option>
> >   <option value="https://example.com"></option>
> >   ...
> > </select>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > byId('settings-presets').addEventListener('change', (e) => {
> >   ...
> > });
> > ```
> 
> How do I view the change you requested?

That is the change I requested.

**Comment by Darth-Ness** [comment]
> > > Thanks for contributing! I have a few changes that I would like to be made.
> > > ```
> > > * Change the buttons to a `select` element. This will save space and make it easier to use.
> > > 
> > > * Refrain from using the `onclick` attribute; instead, inside of the `listeners.js` file, use the `change` event listener to listen for changes of the selection.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Here's an example:
> > > ```
> > > <select id="settings-presets">
> > >   <option value="">Select a preset</option>
> > >   <option value="https://example.com"></option>
> > >   ...
> > > </select>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```js
> > > byId('settings-presets').addEventListener('change', (e) => {
> > >   ...
> > > });
> > > ```
> > 
> > 
> > How do I view the change you requested?
> 
> That is the change I requested.

Okay, the changes I made don't have styling for the dropdowns. So it's in plain-html. Would you mind doing some TailWindCSS? Or do you want me to style it with normal CSS?

**Comment by MystPi** [comment]
I can do some TailwindCSS tomorrow for you.

**Comment by Darth-Ness** [comment]
> I can do some TailwindCSS tomorrow for you.

Thanks you, I will check with hello-smile6 to see whose code we use.

**Comment by hello-smile6** [comment]
> > I can do some TailwindCSS tomorrow for you.
> 
> Thanks you, I will check with hello-smile6 to see whose code we use.

You mean @hello-smile6 ? :)

**Comment by Darth-Ness** [comment]
> > > I can do some TailwindCSS tomorrow for you.
> > 
> > 
> > Thanks you, I will check with hello-smile6 to see whose code we use.
> 
> You mean @hello-smile6 ? :)

Yes, I didn't know you could mention users like that.

**Comment by hello-smile6** [comment]
> > > > I can do some TailwindCSS tomorrow for you.
> > > 
> > > 
> > > Thanks you, I will check with hello-smile6 to see whose code we use.
> > 
> > 
> > You mean @hello-smile6 ? :)
> 
> Yes, I didn't know you could mention users like that.

You can. Also, I check every comment on any PR or issue I care about.

**Comment by Darth-Ness** [comment]
> > > > > I can do some TailwindCSS tomorrow for you.
> > > > 
> > > > 
> > > > Thanks you, I will check with hello-smile6 to see whose code we use.
> > > 
> > > 
> > > You mean @hello-smile6 ? :)
> > 
> > 
> > Yes, I didn't know you could mention users like that.
> 
> You can. Also, I check every comment on any PR or issue I care about.

Okay, whose code should we use?

**Comment by hello-smile6** [comment]
> > > > > > I can do some TailwindCSS tomorrow for you.
> > > > > 
> > > > > 
> > > > > Thanks you, I will check with hello-smile6 to see whose code we use.
> > > > 
> > > > 
> > > > You mean @hello-smile6 ? :)
> > > 
> > > 
> > > Yes, I didn't know you could mention users like that.
> > 
> > 
> > You can. Also, I check every comment on any PR or issue I care about.
> 
> Okay, whose code should we use?

Use mine, but rewrite it to support your dropdown version.

**Comment by Darth-Ness** [comment]
> > > > > > > I can do some TailwindCSS tomorrow for you.
> > > > > > 
> > > > > > 
> > > > > > Thanks you, I will check with hello-smile6 to see whose code we use.
> > > > > 
> > > > > 
> > > > > You mean @hello-smile6 ? :)
> > > > 
> > > > 
> > > > Yes, I didn't know you could mention users like that.
> > > 
> > > 
> > > You can. Also, I check every comment on any PR or issue I care about.
> > 
> > 
> > Okay, whose code should we use?
> 
> Use mine, but rewrite it to support your dropdown version.

Okay, I'll add the dropdowns to the code at some point.

**Comment by MystPi** [comment]
Finished the Tailwind.

**Comment by Darth-Ness** [comment]
Added changes with the dropdowns. Anything else to change?

**Comment by MystPi** [comment]
Do you mind replacing swisscows with Startpage?

**Comment by MystPi** [comment]
Why did you change the styling I did? You removed the flexbox.

**Comment by MystPi** [comment]
I think this would be easier for me just to do it locally and push it to v2.2.4.

**Comment by Darth-Ness** [comment]
Okay then. Also I tried to add Startpage, the problem is that the search results don't show up in the URL.

**Comment by MystPi** [comment]
> Okay then. Also I tried to add Startpage, the problem is that the search results don't show up in the URL.

You use the URL https://startpage.com/sp/search?q=<query\>

**Pull request closed without merging**
