### PR TITLE
Add userchrome support (custom CSS)

### PR DESCRIPTION
**Pull request by ScolderCreations**

### CODE REVIEW

**Comment by MystPi** [comment]
Uh, there's nothing in the `userchrome.css` file.

**Comment by ScolderCreations** [comment]
> Uh, there's nothing in the `userchrome.css` file.

Yup. That’s right. The user is supposed to put stuff there (if they want)

**Comment by MystPi** [comment]
But when the app is built, how would the user change the file?

**Comment by ScolderCreations** [comment]
> But when the app is built, how would the user change the file?

…oh. right. let me think about that.

**Comment by webdev03** [comment]
> > But when the app is built, how would the user change the file?
> 
> …oh. right. let me think about that.

you can store it in the `app.getPath("appdata")` place

**Comment by MystPi** [comment]
I'm going to close this since the user can't edit the `userchrome.css` file. Feel free to comment if there are any updates!

**Pull request closed without merging**
