### PR TITLE
add apple silicon building

### PR DESCRIPTION
**Pull request by webdev03**
this should work, untested though

### CODE REVIEW

**Comment by MystPi** [comment]
Instead of replacing the existing macOS builder, why not add it as an addition?

**Comment by webdev03** [comment]
I think that it is just an extra step in the builder.

**Comment by MystPi** [comment]
I mean instead of replacing `macos-latest`, just append it to the matrix.

**Comment by webdev03** [comment]
macos-11 is just macOS 11 but macos-latest is 10.15 I don't see why we need to have two duplicate builds for 10.15 and 11 (intel)?

**Comment by MystPi** [comment]
Oh, okay.

**Comment by webdev03** [comment]
i was wanting to make sure it worked, because 10.15 doesnt suppose arm as far as i know

**Comment by kccuber-scratch** [comment]
darwin arm64 isn't in the glob, i dont think it'll get uploaded without that

**Comment by webdev03** [comment]
Oh right

**Comment by kccuber-scratch** [comment]
also what about DMG? You had it in Catalyst

**Comment by webdev03** [comment]
I don't know if you want it or not. You can also add PKG support too if you want that. There are a lot of forge makers.
image

**Pull request closed without merging**
