### PR TITLE
Added Super Linter GitHub action

### PR DESCRIPTION
**Pull request by MystPi**
https://github.com/github/super-linter

### CODE REVIEW

**Comment by hello-smile6** [comment]
Nice!

**Review by hello-smile6 — CHANGES_REQUESTED** [review]
Just use <a href="https://github.com/JaydenDev/freecat">Freecat</a> by @JaydenDev, it works better.

**Comment by webdev03** [comment]
Why not prettier? It can run locally too.

**Comment by JaydenDev** [comment]
> Just use [Freecat](https://github.com/JaydenDev/freecat) by @JaydenDev, it works better.

this isn't necessary

**Comment by JaydenDev** [comment]
> Why not [Prettier](http://prettier.io/)? It can run locally too. It's very simple to make a checker for Prettier but I know ScratchA***** can do automatic formatting too.

Prettier broke FreeCat once

**Comment by webdev03** [comment]
Prettier can't break freecat. Or anything.

**Comment by MystPi** [comment]
Prettier formats code; super linter lints it. There's a difference.

**Comment by webdev03** [comment]
https://github.com/MystPi/ninetails/pull/49#issuecomment-995382281

**Pull request merged**
